### ISSUE TITLE
若松の環境構築

### ISSUE THREAD

**Issue by shunya9811** [ChubachiPT2024/manakan#46]
## 概要

各自でElectron+TypeScript+reactの環境を用意してくる

### 何をやるのか
Electron、Electron-forgeのドキュメントをもとに環境を作成する

### なぜやるのか(目的)
モデリングに関して、方向性を見失っているので、一旦開発を進めるために、環境を揃える

## 完成の定義

Electron+TypeScript+reactの環境で、Hello, Worldの表示

**Comment by shunya9811** [comment]
# npmとnpxの違い

## そもそも「npm」「npx」とは
### npm
node package managerの略でNode.js をインストールするとすぐに利用できる依存性+パッケージのマネージャー

・依存性
自分のプロジェクトないし環境に何かしらの影響、作用を与えているもののこと
・パッケージマネージャー
「パッケージ」と「マネージャー」と分けて理解すると、
一つ目の「パッケージ」は様々なシーンで便利に利用できるプログラムの塊のことを指し、「マネージャー」とはそこの管理という意味

### npx
npxとは node package executerの略でパッケージの実行ツールです。 npmとの違いはインストールされてないパッケージでも自動的に探してインストールして実行して、インストールしたパッケージは削除をする

npxとはnpmバージョン5.2.0より同梱されているコマンドで、ローカルインストールしたコマンドを実行するために使われる
つまりこういうこと
npm はnode package manager　＝　パッケージの管理ツール
npx はnode package executer　＝　パッケージの実行を行うツール

参考
https://www.npmjs.com/package/npx
https://qiita.com/kohta9521/items/ee3ed4a2360add80ad79

**Comment by shunya9811** [comment]
# すでに作成されているアプリでのTypeScript+reactを導入するにはどうしたらいいのか
[React with TypeScript](https://www.electronforge.io/guides/framework-integration/react-with-typescript)では、セットアップ段階として、[Webpack + Typescript](https://www.electronforge.io/templates/typescript-+-webpack-template)でアプリを作ることが推奨されている。
そして[Webpack + Typescript](https://www.electronforge.io/templates/typescript-+-webpack-template)では、
```
npm init electron-app@latest my-new-app -- --template=webpack-typescript
```
というコマンドでデフォルト化した設定でアプリを作成している

 すでに作成されているアプリでのTypeScript+reactを導入するにはどうしたらいいのだろうか

**Comment by shunya9811** [comment]
# npm run makeでのエラー
$ npm run make

> testelectrontypereact@1.0.0 make
> electron-forge make

✔ Checking your system
✔ Loading configuration
✖ Resolving make targets
  › Cannot make for deb, the following external binaries need to be installed:
    dpkg, fakeroot
◼ Running package command
◼ Running preMake hook
◼ Making distributables
◼ Running postMake hook

An unhandled rejection has occurred inside Forge:
Error: Cannot make for deb, the following external binaries need to be installed: dpkg, fakeroot
at MakerDeb.ensureExternalBinariesExist (/home/shunya9811/AIIT/PBL/testElectronTypeReact/node_modules/@electron-forge/maker-base/dist/Maker.js:107:19)
    at /home/shunya9811/AIIT/PBL/testElectronTypeReact/node_modules/@electron-forge/core/dist/api/make.js:119:27
    at _Task.taskFn (/home/shunya9811/AIIT/PBL/testElectronTypeReact/node_modules/@electron-forge/tracer/dist/index.js:58:42)
    at _Task.run (/home/shunya9811/AIIT/PBL/testElectronTypeReact/node_modules/listr2/dist/index.cjs:2063:35)

**Comment by shunya9811** [comment]
# npm run make -- --platform=win32でのエラー
$ npm run make -- --platform=win32

> testelectrontypereact@1.0.0 make
> electron-forge make --platform=win32

✔ Checking your system
✔ Loading configuration
✔ Resolving make targets
  › Making for the following targets:
✔ Running package command
  ✔ Preparing to package application
  ✔ Running packaging hooks
    ✔ Running generateAssets hook
    ✔ Running prePackage hook
  ✔ Packaging application
    ✔ Packaging for x64 on win32 [16s]
  ✔ Running postPackage hook
✔ Running preMake hook
❯ Making distributables
  ✖ Making a squirrel distributable for win32/x64
    › You must install both Mono and Wine on non-Windows
◼ Running postMake hook

An unhandled rejection has occurred inside Forge:
Error: You must install both Mono and Wine on non-Windows
at /home/shunya9811/AIIT/PBL/testElectronTypeReact/node_modules/electron-winstaller/lib/index.js:113:31
    at step (/home/shunya9811/AIIT/PBL/testElectronTypeReact/node_modules/electron-winstaller/lib/index.js:56:23)
    at Object.next (/home/shunya9811/AIIT/PBL/testElectronTypeReact/node_modules/electron-winstaller/lib/index.js:37:53)
    at fulfilled (/home/shunya9811/AIIT/PBL/testElectronTypeReact/node_modules/electron-winstaller/lib/index.js:28:58)

**Comment by shunya9811** [comment]
# 環境
C:\Users\rainm>wsl --version
WSL バージョン: 2.1.5.0
カーネル バージョン: 5.15.146.1-2
WSLg バージョン: 1.0.60
MSRDC バージョン: 1.2.5105
Direct3D バージョン: 1.611.1-81528511
DXCore バージョン: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows バージョン: 10.0.22631.3737

$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

$ node -v
v20.13.1

$ npm -v
10.8.1

**Comment by shunya9811** [comment]
# npm run makeでのエラー
$ npm run make

> testelectrontypereact@1.0.0 make
> electron-forge make

✔ Checking your system
✔ Loading configuration
✖ Resolving make targets
  › Cannot make for deb, the following external binaries need to be installed:
    dpkg, fakeroot
◼ Running package command
◼ Running preMake hook
◼ Making distributables
◼ Running postMake hook

An unhandled rejection has occurred inside Forge:
Error: Cannot make for deb, the following external binaries need to be installed: dpkg, fakeroot
at MakerDeb.ensureExternalBinariesExist (/home/shunya9811/AIIT/PBL/testElectronTypeReact/node_modules/@electron-forge/maker-base/dist/Maker.js:107:19)
    at /home/shunya9811/AIIT/PBL/testElectronTypeReact/node_modules/@electron-forge/core/dist/api/make.js:119:27
    at _Task.taskFn (/home/shunya9811/AIIT/PBL/testElectronTypeReact/node_modules/@electron-forge/tracer/dist/index.js:58:42)
    at _Task.run (/home/shunya9811/AIIT/PBL/testElectronTypeReact/node_modules/listr2/dist/index.cjs:2063:35)

**Comment by shunya9811** [comment]
# npm run make -- --platform=win32
$ npm run make -- --platform=win32

> testelectrontypereact@1.0.0 make
> electron-forge make --platform=win32

✔ Checking your system
✔ Loading configuration
✔ Resolving make targets
  › Making for the following targets:
✔ Running package command
  ✔ Preparing to package application
  ✔ Running packaging hooks
    ✔ Running generateAssets hook
    ✔ Running prePackage hook
  ✔ Packaging application
    ✔ Packaging for x64 on win32 [3s]
  ✔ Running postPackage hook
✔ Running preMake hook
❯ Making distributables
  ✖ Making a squirrel distributable for win32/x64
    › You must install both Mono and Wine on non-Windows
◼ Running postMake hook

An unhandled rejection has occurred inside Forge:
Error: You must install both Mono and Wine on non-Windows
at /home/shunya9811/AIIT/PBL/testElectronTypeReact/node_modules/electron-winstaller/lib/index.js:113:31
    at step (/home/shunya9811/AIIT/PBL/testElectronTypeReact/node_modules/electron-winstaller/lib/index.js:56:23)
    at Object.next (/home/shunya9811/AIIT/PBL/testElectronTypeReact/node_modules/electron-winstaller/lib/index.js:37:53)
    at fulfilled (/home/shunya9811/AIIT/PBL/testElectronTypeReact/node_modules/electron-winstaller/lib/index.js:28:58)

**Comment by shunya9811** [comment]
以下手順で、Electron + TypeScript + reactの環境をセットアップ
npm init electron-app@latest my-new-app -- --template=vite-typescript

tsconfig.jsonに
キーバリュー"jsx": "react-jsx" を"compilerOptions" セクションに追加

npm install --save react react-dom
npm install --save-dev @types/react @types/react-dom

src/app.tsxとsrc/renderer.tsにコードを追加

### 参考
https://www.electronforge.io/templates/typescript-+-webpack-template
https://www.electronforge.io/guides/framework-integration/react-with-typescript


ここまでやって、npm run startしたところ、以下エラー
[28191:0614/195004.101680:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)

[28191:0614/195004.101837:ERROR:CONSOLE(1)] "Request Autofill.setAddresses failed. {"code":-32601,"message":"'Autofill.setAddresses' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)

バグとして、解消されていないみたい
https://github.com/electron/electron/issues/41614

**Comment by shunya9811** [comment]
# Electronウィンドウのコンソール中に以下エラーがある

Warning: createRoot(): Creating roots directly with document.body is discouraged, since its children are often manipulated by third-party scripts and browser extensions. This may lead to subtle reconciliation issues. Try using a container element created for your app.

これは、renderer.tsで以下のように直接app.tsxをインポートしているから
```
import './app';
```

ただこれはelectron-forgeの公式に則った方法なんだが
https://www.electronforge.io/guides/framework-integration/react-with-typescript

**Comment by shunya9811** [comment]
npm init electron-app@latest . -- --template=vite-typescript

tsconfig.jsonに
キーバリュー"jsx": "react-jsx" を"compilerOptions" セクションに追加

npm install --save react react-dom
npm install --save-dev @types/react @types/react-dom

src/app.tsxとsrc/renderer.tsにコードを追加

参考
https://www.electronforge.io/templates/typescript-+-webpack-template
https://www.electronforge.io/guides/framework-integration/react-with-typescript

**Comment by shunya9811** [comment]
# ESLint
### 基本構文
```
npx eslint [options] [file|dir|glob]*
```

### 特定のファイル
```
npx eslint ./path/to/file
```

### 現在のディレクトリ
```
npx eslint .
```

### チェックと修正まで行う
```
npx eslint --fix ./path/to/file
```

### Script的には
```
npm run lint
```
現在は、拡張子が.tsと.tsxのファイルの、構文エラーや不具合になりそうな箇所を警告

https://zenn.dev/harusame0616/articles/42a52bc0f9843c
